// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.187
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddAnyFilePkgString = "27dd9dea-6dd2-403e-929d-3ff20d896c5e";
        public const string guidAddAnyFileCmdSetString = "32af8a17-bbbc-4c56-877e-fc6c6575a8cf";
        public static Guid guidAddAnyFilePkg = new Guid(guidAddAnyFilePkgString);
        public static Guid guidAddAnyFileCmdSet = new Guid(guidAddAnyFileCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidMyCommand = 0x0100;
    }
}
