// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
    internal sealed partial class Vsix
    {
        public const string Id = "d48e8f25-661b-4970-8b66-03f051ba5fc3";
        public const string Name = "Add New File (64-bit)";
        public const string Description = @"The fastest and easiest way to add new files to any project - including files that start with a dot";
        public const string Language = "en-US";
        public const string Version = "4.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "file, add, template";
    }
}
