// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.AddAnyFile
{
				static class Vsix
				{
								public const string Id = "2E78AA18-E864-4FBB-B8C8-6186FC865DB3";
								public const string Name = "Add New File";
								public const string Description = @"The fastest and easiest way to add new files to any project - including files that start with a dot";
								public const string Language = "en-US";
								public const string Version = "3.5";
								public const string Author = "Mads Kristensen";
								public const string Tags = "file, add, template";
				}
}
